// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utpikfeynhjgbtqcgycg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cGlrZmV5bmhqZ2J0cWNneWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTUzNTksImV4cCI6MjA2MjA5MTM1OX0.FX0Rkk3aHbNWv9mKNXp_ZInB8y3ruQ3N2mq-cXq1OEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);